export enum AreaCasa {
  CUCINA = 'CUCINA',
  SOGGIORNO = 'SOGGIORNO',
  SALOTTO = 'SALOTTO',
  CAMERA_DA_LETTO = 'CAMERA_DA_LETTO',
  CAMERETTA = 'CAMERETTA',
  BAGNO = 'BAGNO',
  INGRESSO = 'INGRESSO',
  CORRIDOIO_DISIMPEGNO = 'CORRIDOIO_DISIMPEGNO',
  RIPOSTIGLIO_LAVANDERIA = 'RIPOSTIGLIO_LAVANDERIA',
  STUDIO = 'STUDIO',
  TERRAZZO_BALCONE = 'TERRAZZO_BALCONE',
  GIARDINO_ESTERNO = 'GIARDINO_ESTERNO',
  GARAGE_BOX = 'GARAGE_BOX',
  CANTINA_TAVERNA = 'CANTINA_TAVERNA',
  STANZA_COMUNE = 'STANZA_COMUNE'
}

export interface Stanza {
  id?: string;
  tipologia: AreaCasa;
}
